#config/s3.yml

development:
  access_key_id: AKIAJ37JWBBNXXWMGMMQ
  secret_access_key: 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
  bucket: blog_as3_vcabansag
production:
  access_key_id: AKIAJ37JWBBNXXWMGMMQ
  secret_access_key: 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
  bucket: blog_as3_vcabansag
